# Generated by Django 2.2.6 on 2019-11-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('NombreTienda', models.CharField(max_length=40)),
                ('Rut_Tienda', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Creacion', models.DateField(auto_now_add=True)),
                ('Actualizacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProducto', models.CharField(max_length=80)),
                ('Precio', models.CharField(max_length=8)),
                ('Descripcion', models.TextField()),
                ('Marca', models.CharField(max_length=20)),
                ('Imagen', models.ImageField(upload_to='ImagenProductos')),
                ('Creacion', models.DateField(auto_now_add=True)),
                ('Actualizacion', models.DateField(auto_now=True)),
                ('Tiendas', models.ManyToManyField(to='BDTodoEstetica.Tienda')),
            ],
        ),
    ]
