# Generated by Django 2.2.6 on 2019-11-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDTodoEstetica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='Actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='Creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
