# Generated by Django 2.2.6 on 2019-11-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BDTodoEstetica', '0002_auto_20191101_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Tiendas',
            new_name='Tienda',
        ),
    ]
