# Generated by Django 2.2.6 on 2019-11-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDTodoEstetica', '0003_auto_20191107_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Tienda',
        ),
        migrations.AddField(
            model_name='producto',
            name='Tienda',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
