# Generated by Django 2.2.6 on 2019-11-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDTodoEstetica', '0004_auto_20191108_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Tienda',
        ),
        migrations.AddField(
            model_name='producto',
            name='Tienda',
            field=models.ManyToManyField(to='BDTodoEstetica.Tienda'),
        ),
    ]
