# Generated by Django 2.2.6 on 2019-11-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDTodoEstetica', '0005_auto_20191108_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='MediaProductos'),
        ),
    ]
